### ISSUE TITLE
Make Battery Percentage Indicator Accurate

### ISSUE THREAD

**Issue by aaravgarg** [BasedHardware/omi#2782]
battery indicator on CV1 is very unstable and keeps jumping up and down as reported by many users.

also please fix that it shows -1% on connecting, users freak out when they see that

**Comment by BasedNight** [comment]
Is this bounty still active? I believe I have a working fix for this issue and #3041. I will however need assistance testing on a CV1; I only have the DK2.

**Comment by aaravgarg** [comment]
> Is this bounty still active? I believe I have a working fix for this issue and [#3041](https://github.com/BasedHardware/omi/issues/3041). I will however need assistance testing on a CV1; I only have the DK2.

Yes its active

**Comment by BasedNight** [comment]
How much is the bounty?

**Comment by aaravgarg** [comment]
> How much is the bounty?

added bounty, timeframe: 1 week

goal: the battery indicator in the app for CV1 should be near 100% accurate

right now it fluctuates a lot, goes up and down constantly and is hella inaccurate all the time

**Comment by BasedNight** [comment]
This bug should be fixed by #3127

The initial read (showing -1%) will presumably be fixed separately by #3081

**Comment by MithilSaiReddy** [comment]
is this open ?

**Comment by aaravgarg** [comment]
> is this open ?

Yes

**Comment by aaravgarg** [comment]
battery indicator is still broken, its very unstable and needs to be fixed.

watch for example: https://youtu.be/1tIr-ikYKaE?t=454

**Comment by beastoin** [comment]
man 3.0.7 is far different from the latest - 3.0.12 firmware, which has tons of improvements on the battery indicator. suggest they do the upgrade first.

**Comment by aaravgarg** [comment]
> man 3.0.7 is far different from the latest - 3.0.12 firmware, which has tons of improvements on the battery indicator. suggest they do the upgrade first.

Can we enforce firmware updates, that way we won't have people complaining from broken versions

Also battery still jumps up and down for me sometimes, especially when putting to charge and removing from it

**Comment by beastoin** [comment]
>Also battery still jumps up and down for me sometimes, especially when putting to charge and removing from it

cap me a video to see how bad it is.

**Comment by kodjima33** [comment]
can @TuEmb do this?

**Comment by TuEmb** [comment]
I’ll take this task. Let me perform an initial analysis to identify the root cause behind the unstable battery indicator.
We have 2 problems here:

-  -1%showing on the phone app (I believe it's not related to the firmware side) --> we need update the phone app to get the battery level whenever we connect to the device.
- The battery level jumps up/down --> it's not stable at all. I think I will take a look at the ADC convert in the firmware side to increase the accuracy and apply an algorithm for it
